apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: response
  labels:
    app: response
spec:
  to:
    kind: Service
    name: response
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
